version: '3.8'

services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app-network

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ "1025:1025", "1080:1080" ]

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
