<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSHcJrK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSHcJrK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSHcJrK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSHcJrK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGSHcJrK\App_KernelDevDebugContainer([
    'container.build_hash' => 'GSHcJrK',
    'container.build_id' => 'c33f484b',
    'container.build_time' => 1713775590,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSHcJrK');
