<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNDwfux8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNDwfux8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNDwfux8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNDwfux8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNDwfux8\App_KernelDevDebugContainer([
    'container.build_hash' => 'NDwfux8',
    'container.build_id' => 'ea3aebeb',
    'container.build_time' => 1713780588,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNDwfux8');
